"""add priority to budget allocation

Revision ID: 3343e46e8828
Revises: a7f04b2c035d
Create Date: 2026-08-26 23:00:17.999665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3343e46e8828'
down_revision = 'a7f04b2c035d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False, server_default='5'))

    with op.batch_alter_table('budget_allocation', schema=None) as batch_op:
        batch_op.alter_column('priority', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_allocation', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
