"""add language to user

Revision ID: 7820d3383b89
Revises: d8fc08676bd7
Create Date: 2026-09-01 13:18:08.424018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7820d3383b89'
down_revision = 'd8fc08676bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=False, server_default='en'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('language', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
