"""add created_at and checkin_email_sent to user

Revision ID: d8fc08676bd7
Revises: 7b5375e9e6f1
Create Date: 2026-09-01 10:08:08.018872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fc08676bd7'
down_revision = '7b5375e9e6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        # Backfill existing users as already-checked-in so the new automation only
        # applies to people who sign up from here on, not everyone who already has
        # an account (they don't need a "how's your first week going" email).
        batch_op.add_column(sa.Column('checkin_email_sent', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at', server_default=None)
        batch_op.alter_column('checkin_email_sent', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('checkin_email_sent')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
