"""add debt_id to transaction for linking debt payments

Revision ID: ff272316e06d
Revises: d6886322d09a
Create Date: 2026-08-13 14:42:38.145973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff272316e06d'
down_revision = 'd6886322d09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_debt_id_debt', 'debt', ['debt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_debt_id_debt', type_='foreignkey')
        batch_op.drop_column('debt_id')

    # ### end Alembic commands ###
